package view;

import model.Def_DAO;
import static model.Variables_DAO.l;
import static model.Variables_DAO.m;
import static model.Variables_DAO.n;
import static model.Variables_DAO.o;
import static model.Variables_DAO.p;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alunos
 */
public class Window_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Window_GUI
     */
    public Window_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AtendimentoNormal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_atendNomal = new javax.swing.JLabel();
        lbl_num = new javax.swing.JLabel();
        lbl_NormPref = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_old1 = new javax.swing.JLabel();
        lbl_old4 = new javax.swing.JLabel();
        lbl_old3 = new javax.swing.JLabel();
        lbl_old2 = new javax.swing.JLabel();
        btn_geraNormal = new javax.swing.JButton();
        btn_geraPref = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        AtendimentoNormal.setLayout(null);

        jPanel2.setLayout(null);

        lbl_atendNomal.setFont(new java.awt.Font("Arial", 1, 35)); // NOI18N
        lbl_atendNomal.setText("Atendimento ");
        jPanel2.add(lbl_atendNomal);
        lbl_atendNomal.setBounds(80, 10, 390, 41);

        lbl_num.setFont(new java.awt.Font("Arial", 1, 100)); // NOI18N
        lbl_num.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_num.setText("___");
        jPanel2.add(lbl_num);
        lbl_num.setBounds(80, 110, 290, 141);

        lbl_NormPref.setFont(new java.awt.Font("Liberation Sans", 1, 35)); // NOI18N
        jPanel2.add(lbl_NormPref);
        lbl_NormPref.setBounds(80, 60, 290, 50);

        AtendimentoNormal.add(jPanel2);
        jPanel2.setBounds(0, 0, 400, 250);

        jPanel3.setLayout(null);

        lbl_old1.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        lbl_old1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_old1.setText("___");
        jPanel3.add(lbl_old1);
        lbl_old1.setBounds(140, 10, 160, 50);

        lbl_old4.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        lbl_old4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_old4.setText("___");
        jPanel3.add(lbl_old4);
        lbl_old4.setBounds(140, 160, 160, 50);

        lbl_old3.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        lbl_old3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_old3.setText("___");
        jPanel3.add(lbl_old3);
        lbl_old3.setBounds(140, 110, 160, 50);

        lbl_old2.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        lbl_old2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_old2.setText("___");
        jPanel3.add(lbl_old2);
        lbl_old2.setBounds(140, 60, 160, 50);

        AtendimentoNormal.add(jPanel3);
        jPanel3.setBounds(0, 250, 400, 250);

        jPanel1.add(AtendimentoNormal);
        AtendimentoNormal.setBounds(0, 0, 410, 500);

        btn_geraNormal.setText("Convencional");
        btn_geraNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_geraNormalActionPerformed(evt);
            }
        });
        jPanel1.add(btn_geraNormal);
        btn_geraNormal.setBounds(530, 20, 270, 50);

        btn_geraPref.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_geraPref.setText("Preferencial");
        btn_geraPref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_geraPrefActionPerformed(evt);
            }
        });
        jPanel1.add(btn_geraPref);
        btn_geraPref.setBounds(530, 270, 270, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_geraNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_geraNormalActionPerformed
        model.Def_DAO.Armazena(model.Def_DAO.Sorteia());
        model.Def_DAO.Mostra();
    }//GEN-LAST:event_btn_geraNormalActionPerformed

    private void btn_geraPrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_geraPrefActionPerformed
        model.Def_DAO.ArmazenaCadeirante(model.Def_DAO.Sorteia());
        model.Def_DAO.MostraPreferencial();
    }//GEN-LAST:event_btn_geraPrefActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AtendimentoNormal;
    private javax.swing.JButton btn_geraNormal;
    private javax.swing.JButton btn_geraPref;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JLabel lbl_NormPref;
    public static javax.swing.JLabel lbl_atendNomal;
    public static javax.swing.JLabel lbl_num;
    public static javax.swing.JLabel lbl_old1;
    public static javax.swing.JLabel lbl_old2;
    public static javax.swing.JLabel lbl_old3;
    public static javax.swing.JLabel lbl_old4;
    // End of variables declaration//GEN-END:variables
}
